### PR TITLE
:zap: will like to :alien: deleteALl :wrench:

### PR DESCRIPTION
**Pull request by devfemibadmus**
I added a `deleteAll` function that allows users to delete all items or a specific range of items by passing an optional range (e.g., `"0-5"`). If no range is provided, it deletes everything.

### CODE REVIEW

**Comment by AbdulConsole** [comment]
Ye ye yeah

**Comment by AbdulConsole** [comment]
I kinda like the way you mix emojis into your commit messages 😉

**Comment by devfemibadmus** [comment]
> I kinda like the way you mix emojis into your commit messages 😉

lol i have a script for that instead of manually doing all time

**Comment by AbdulConsole** [comment]
Share link .. lemme learn

**Pull request merged**
